# Generated by Django 4.1.7 on 2023-03-21 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2023, 3, 21, 15, 43, 16, 586750, tzinfo=datetime.timezone.utc)),
        ),
    ]
